using Helion.Util;

namespace Helion.Resource.Maps.Actions
{
    public static class ActionSpecialHelper
    {
        /// <summary>
        /// Checks whether a case-insensitive name is an action special name.
        /// </summary>
        /// <param name="name">The name to check.</param>
        /// <returns>True if it is, false if not.</returns>
        public static bool Exists(UpperString name)
        {
            switch (name.String)
            {
            case "ACS_EXECUTE":
            case "ACS_EXECUTEALWAYS":
            case "ACS_EXECUTEWITHRESULT":
            case "ACS_LOCKEDEXECUTE":
            case "ACS_LOCKEDEXECUTEDOOR":
            case "ACS_SUSPEND":
            case "ACS_TERMINATE":
            case "AUTOSAVE":
            case "CEILING_CRUSHANDRAISEA":
            case "CEILING_CRUSHANDRAISE":
            case "CEILING_CRUSHANDRAISEDIST":
            case "CEILING_CRUSHANDRAISESILENTA":
            case "CEILING_CRUSHANDRAISESILENTDIST":
            case "CEILING_CRUSHRAISEANDSTAYA":
            case "CEILING_CRUSHRAISEANDSTAY":
            case "CEILING_CRUSHRAISEANDSTAYSILA":
            case "CEILING_CRUSHSTOP":
            case "CEILING_LOWERANDCRUSH":
            case "CEILING_LOWERANDCRUSHDIST":
            case "CEILING_LOWERBYTEXTURE":
            case "CEILING_LOWERBYVALUE":
            case "CEILING_LOWERBYVALUETIMES8":
            case "CEILING_LOWERINSTANT":
            case "CEILING_LOWERTOFLOOR":
            case "CEILING_LOWERTOHIGHESTFLOOR":
            case "CEILING_LOWERTOLOWEST":
            case "CEILING_LOWERTONEAREST":
            case "CEILING_MOVETOVALUEANDCRUSH":
            case "CEILING_MOVETOVALUE":
            case "CEILING_MOVETOVALUETIMES8":
            case "CEILING_RAISEBYTEXTURE":
            case "CEILING_RAISEBYVALUE":
            case "CEILING_RAISEBYVALUETIMES8":
            case "CEILING_RAISEINSTANT":
            case "CEILING_RAISETOHIGHEST":
            case "CEILING_RAISETOHIGHESTFLOOR":
            case "CEILING_RAISETOLOWEST":
            case "CEILING_RAISETONEAREST":
            case "CEILING_STOP":
            case "CEILING_TOFLOORINSTANT":
            case "CEILING_TOHIGHESTINSTANT":
            case "CEILING_WAGGLE":
            case "CHANGECAMERA":
            case "CHANGESKILL":
            case "CLEARFORCEFIELD":
            case "DAMAGETHING":
            case "DOOR_ANIMATEDCLOSE":
            case "DOOR_ANIMATED":
            case "DOOR_CLOSE":
            case "DOOR_CLOSEWAITOPEN":
            case "DOOR_LOCKEDRAISE":
            case "DOOR_OPEN":
            case "DOOR_RAISE":
            case "DOOR_WAITCLOSE":
            case "DOOR_WAITRAISE":
            case "ELEVATOR_LOWERTONEAREST":
            case "ELEVATOR_MOVETOFLOOR":
            case "ELEVATOR_RAISETONEAREST":
            case "EXIT_NORMAL":
            case "EXIT_SECRET":
            case "EXTRAFLOOR_LIGHTONLY":
            case "FLOORANDCEILING_LOWERBYVALUE":
            case "FLOORANDCEILING_LOWERRAISE":
            case "FLOORANDCEILING_RAISEBYVALUE":
            case "FLOOR_CRUSHSTOP":
            case "FLOOR_DONUT":
            case "FLOOR_LOWERBYTEXTURE":
            case "FLOOR_LOWERBYVALUE":
            case "FLOOR_LOWERBYVALUETIMES8":
            case "FLOOR_LOWERINSTANT":
            case "FLOOR_LOWERTOHIGHESTEE":
            case "FLOOR_LOWERTOHIGHEST":
            case "FLOOR_LOWERTOLOWESTCEILING":
            case "FLOOR_LOWERTOLOWEST":
            case "FLOOR_LOWERTOLOWESTTXTY":
            case "FLOOR_LOWERTONEAREST":
            case "FLOOR_MOVETOVALUEANDCRUSH":
            case "FLOOR_MOVETOVALUE":
            case "FLOOR_MOVETOVALUETIMES8":
            case "FLOOR_RAISEANDCRUSHDOOM":
            case "FLOOR_RAISEANDCRUSH":
            case "FLOOR_RAISEBYTEXTURE":
            case "FLOOR_RAISEBYVALUE":
            case "FLOOR_RAISEBYVALUETIMES8":
            case "FLOOR_RAISEBYVALUETXTY":
            case "FLOOR_RAISEINSTANT":
            case "FLOOR_RAISETOCEILING":
            case "FLOOR_RAISETOHIGHEST":
            case "FLOOR_RAISETOLOWESTCEILING":
            case "FLOOR_RAISETOLOWEST":
            case "FLOOR_RAISETONEAREST":
            case "FLOOR_STOP":
            case "FLOOR_TOCEILINGINSTANT":
            case "FLOOR_TRANSFERNUMERIC":
            case "FLOOR_TRANSFERTRIGGER":
            case "FLOOR_WAGGLE":
            case "FORCEFIELD":
            case "FS_EXECUTE":
            case "GENERIC_CEILING":
            case "GENERIC_CRUSHER2":
            case "GENERIC_CRUSHER":
            case "GENERIC_DOOR":
            case "GENERIC_FLOOR":
            case "GENERIC_LIFT":
            case "GENERIC_STAIRS":
            case "GLASSBREAK":
            case "HEALTHING":
            case "LIGHT_CHANGETOVALUE":
            case "LIGHT_FADE":
            case "LIGHT_FLICKER":
            case "LIGHT_FORCELIGHTNING":
            case "LIGHT_GLOW":
            case "LIGHT_LOWERBYVALUE":
            case "LIGHT_MAXNEIGHBOR":
            case "LIGHT_MINNEIGHBOR":
            case "LIGHT_RAISEBYVALUE":
            case "LIGHT_STOP":
            case "LIGHT_STROBEDOOM":
            case "LIGHT_STROBE":
            case "LINE_ALIGNCEILING":
            case "LINE_ALIGNFLOOR":
            case "LINE_HORIZON":
            case "LINE_MIRROR":
            case "LINE_SETBLOCKING":
            case "LINE_SETIDENTIFICATION":
            case "LINE_SETPORTAL":
            case "LINE_SETPORTALTARGET":
            case "LINE_SETTEXTUREOFFSET":
            case "LINE_SETTEXTURESCALE":
            case "NOISEALERT":
            case "PILLAR_BUILDANDCRUSH":
            case "PILLAR_BUILD":
            case "PILLAR_OPEN":
            case "PLANE_ALIGN":
            case "PLANE_COPY":
            case "PLAT_DOWNBYVALUE":
            case "PLAT_DOWNWAITUPSTAYLIP":
            case "PLAT_DOWNWAITUPSTAY":
            case "PLAT_PERPETUALRAISELIP":
            case "PLAT_PERPETUALRAISE":
            case "PLAT_RAISEANDSTAYTX0":
            case "PLAT_STOP":
            case "PLAT_TOGGLECEILING":
            case "PLAT_UPBYVALUE":
            case "PLAT_UPBYVALUESTAYTX":
            case "PLAT_UPNEARESTWAITDOWNSTAY":
            case "PLAT_UPWAITDOWNSTAY":
            case "POINTPUSH_SETFORCE":
            case "POLYOBJ_DOORSLIDE":
            case "POLYOBJ_DOORSWING":
            case "POLYOBJ_EXPLICITLINE":
            case "POLYOBJ_MOVE":
            case "POLYOBJ_MOVETIMES8":
            case "POLYOBJ_MOVETO":
            case "POLYOBJ_MOVETOSPOT":
            case "POLYOBJ_OR_MOVE":
            case "POLYOBJ_OR_MOVETIMES8":
            case "POLYOBJ_OR_MOVETO":
            case "POLYOBJ_OR_MOVETOSPOT":
            case "POLYOBJ_OR_ROTATELEFT":
            case "POLYOBJ_OR_ROTATERIGHT":
            case "POLYOBJ_ROTATELEFT":
            case "POLYOBJ_ROTATERIGHT":
            case "POLYOBJ_STARTLINE":
            case "POLYOBJ_STOP":
            case "RADIUS_QUAKE":
            case "SCROLL_CEILING":
            case "SCROLL_FLOOR":
            case "SCROLL_TEXTURE_BOTH":
            case "SCROLL_TEXTURE_DOWN":
            case "SCROLL_TEXTURE_LEFT":
            case "SCROLL_TEXTURE_MODEL":
            case "SCROLL_TEXTURE_OFFSETS":
            case "SCROLL_TEXTURE_RIGHT":
            case "SCROLL_TEXTURE_UP":
            case "SCROLL_WALL":
            case "SECTOR_ATTACH3DMIDTEX":
            case "SECTOR_CHANGEFLAGS":
            case "SECTOR_CHANGESOUND":
            case "SECTOR_COPYSCROLLER":
            case "SECTOR_SET3DFLOOR":
            case "SECTOR_SETCEILINGGLOW":
            case "SECTOR_SETCEILINGPANNING":
            case "SECTOR_SETCEILINGSCALE2":
            case "SECTOR_SETCEILINGSCALE":
            case "SECTOR_SETCOLOR":
            case "SECTOR_SETCONTENTS":
            case "SECTOR_SETCURRENT":
            case "SECTOR_SETDAMAGE":
            case "SECTOR_SETFADE":
            case "SECTOR_SETFLOORGLOW":
            case "SECTOR_SETFLOORPANNING":
            case "SECTOR_SETFLOORSCALE2":
            case "SECTOR_SETFLOORSCALE":
            case "SECTOR_SETFRICTION":
            case "SECTOR_SETGRAVITY":
            case "SECTOR_SETLINK":
            case "SECTOR_SETPLANEREFLECTION":
            case "SECTOR_SETPORTAL":
            case "SECTOR_SETROTATION":
            case "SECTOR_SETTRANSLUCENT":
            case "SECTOR_SETWIND":
            case "SENDTOCOMMUNICATOR":
            case "SETGLOBALFOGPARAMETER":
            case "SETPLAYERPROPERTY":
            case "STAIRS_BUILDDOWNDOOM":
            case "STAIRS_BUILDDOWNDOOMSYNC":
            case "STAIRS_BUILDDOWN":
            case "STAIRS_BUILDDOWNSYNC":
            case "STAIRS_BUILDUPDOOMCRUSH":
            case "STAIRS_BUILDUPDOOM":
            case "STAIRS_BUILDUPDOOMSYNC":
            case "STAIRS_BUILDUP":
            case "STAIRS_BUILDUPSYNC":
            case "STARTCONVERSATION":
            case "STATIC_INIT":
            case "TELEPORT_ENDGAME":
            case "TELEPORTGROUP":
            case "TELEPORTINSECTOR":
            case "TELEPORT_LINE":
            case "TELEPORT_NEWMAP":
            case "TELEPORT_NOFOG":
            case "TELEPORT_NOSTOP":
            case "TELEPORTOTHER":
            case "TELEPORT":
            case "TELEPORT_ZOMBIECHANGER":
            case "THING_ACTIVATE":
            case "THING_CHANGETID":
            case "THING_DAMAGE":
            case "THING_DEACTIVATE":
            case "THING_DESTROY":
            case "THING_HATE":
            case "THING_MOVE":
            case "THING_PROJECTILEAIMED":
            case "THING_PROJECTILEGRAVITY":
            case "THING_PROJECTILEINTERCEPT":
            case "THING_PROJECTILE":
            case "THING_RAISE":
            case "THING_REMOVE":
            case "THING_SETCONVERSATION":
            case "THING_SETGOAL":
            case "THING_SETSPECIAL":
            case "THING_SETTRANSLATION":
            case "THING_SPAWNFACING":
            case "THING_SPAWNNOFOG":
            case "THING_SPAWN":
            case "THING_STOP":
            case "THRUSTTHING":
            case "THRUSTTHINGZ":
            case "TRANSFER_CEILINGLIGHT":
            case "TRANSFER_FLOORLIGHT":
            case "TRANSFER_HEIGHTS":
            case "TRANSFER_WALLLIGHT":
            case "TRANSLUCENTLINE":
            case "USEPUZZLEITEM":
                return true;
            default:
                return false;
            }
        }
    }
}
