using System.Collections.Generic;
using System.Linq;
using Helion.Core.Resource.Decorate.Definitions.Properties.Enums;
using Helion.Core.Resource.Decorate.Definitions.Properties.Types;
using Helion.Core.Resource.Maps.Actions;
using Helion.Core.Util;
using UnityEngine;

namespace Helion.Core.Resource.Decorate.Definitions.Properties
{
    public class ActorProperties
    {
        public int? Accuracy;
        public ThingSpecialActivationType Activation = ThingSpecialActivationType.Default;
        public Optional<UpperString> ActiveSound = Optional<UpperString>.Empty();
        public float Alpha = 1.0f;
        public SpecialArgs Args = new SpecialArgs();
        public Optional<UpperString> AttackSound = Optional<UpperString>.Empty();
        public Color? BloodColor;
        public readonly List<UpperString> BloodType = new List<UpperString>();
        public int BounceCount = int.MaxValue;
        public float BounceFactor = 0.7f;
        public Optional<UpperString> BounceSound = Optional<UpperString>.Empty();
        public BounceType BounceType = BounceType.None;
        public int? BurnHeight;
        public int? CameraHeight;
        public int ConversationID;
        public Optional<UpperString> CrushPainSound = Optional<UpperString>.Empty();
        public int Damage;
        public readonly DamageFactor DamageFactor = new DamageFactor();
        public Optional<UpperString> DamageType = Optional<UpperString>.Empty();
        public int? DeathHeight;
        public Optional<UpperString> DeathSound = Optional<UpperString>.Empty();
        public Optional<UpperString> DeathType = Optional<UpperString>.Empty();
        public Optional<UpperString> Decal = Optional<UpperString>.Empty();
        public int? DefThreshold;
        public int? DesignatedTeam;
        public Optional<UpperString> DistanceCheck = Optional<UpperString>.Empty();
        public List<DropItem> DropItem = new List<DropItem>();
        public float? FastSpeed;
        public int FloatBobPhase;
        public float FloatBobStrength = 1.0f;
        public float FloatSpeed = 4.0f;
        public float Friction = 1.0f;
        public int FriendlySeeBlocks = 10;
        public int? ExplosionDamage;
        public int? ExplosionRadius;
        public readonly List<string> Game = new List<string>();
        public int? GibHealth;
        public float Gravity = 1.0f;
        public int Health = 1000;
        public int Height = 16;
        public Optional<string> HitObituary = Optional<string>.Empty();
        public Optional<UpperString> HowlSound = Optional<UpperString>.Empty();
        public int Mass = 100;
        public int MaxStepHeight = 24;
        public int MaxDropOffHeight = 24;
        public int? MaxTargetRange;
        public int? MeleeDamage;
        public int MeleeRange = 44;
        public Optional<UpperString> MeleeSound = Optional<UpperString>.Empty();
        public int? MeleeThreshold;
        public int MinMissileChance = 200;
        public int? MissileHeight;
        public Optional<UpperString> MissileType = Optional<UpperString>.Empty();
        public Optional<string> Obituary = Optional<string>.Empty();
        public readonly PainChance PainChance = new PainChance();
        public int PainThreshold;
        public Optional<UpperString> PainType = Optional<UpperString>.Empty();
        public PoisonDamage? PoisonDamage;
        public Optional<UpperString> PoisonDamageType = Optional<UpperString>.Empty();
        public int? ProjectileKickBack;
        public int? ProjectilePassHeight;
        public float PushFactor = 0.25f;
        public int Radius = 20;
        public float RadiusDamageFactor = 1.0f;
        public int ReactionTime = 8;
        public float RenderRadius;
        public RenderStyle RenderStyle = RenderStyle.Normal;
        public int RipLevelMax;
        public int RipLevelMin;
        public int? RipperLevel;
        public float Scale = 1.0f;
        public float SelfDamageFactor = 1.0f;
        public int SpawnID;
        public Optional<SpawnInfo> SpawnInfo = Optional<SpawnInfo>.Empty();
        public Optional<UpperString> Species = Optional<UpperString>.Empty();
        public float Speed;
        public int? SpriteAngle;
        public int? SpriteRotation;
        public int? Stamina;
        public float StealthAlpha;
        public Color? StencilColor;
        public Optional<UpperString> Tag = Optional<UpperString>.Empty();
        public UpperString TeleFogDestType = "TELEPORTFOG";
        public UpperString TeleFogSourceType = "TELEPORTFOG";
        public int Threshold;
        public Translation Translation = new Translation();
        public DecorateRange<int>? VisibleAngles;
        public DecorateRange<int>? VisiblePitch;
        public List<UpperString> VisibleToPlayerClass;
        public int? VisibleToTeam;
        public float? VSpeed;
        public float WallBounceFactor = 0.7f;
        public int? WeaveIndexXY;
        public int? WeaveIndexZ;
        public int WoundHealth;
        public float XScale = 1.0f;
        public float YScale = 1.0f;

        public ActorProperties()
        {
        }

        public ActorProperties(ActorProperties other)
        {
            Accuracy = other.Accuracy;
            Activation = other.Activation;
            ActiveSound = other.ActiveSound.Copy();
            Alpha = other.Alpha;
            AttackSound = other.AttackSound.Copy();
            Args = new SpecialArgs(other.Args);
            BloodColor = other.BloodColor;
            BloodType = new List<UpperString>(other.BloodType);
            BounceCount = other.BounceCount;
            BounceFactor = other.BounceFactor;
            BounceSound = other.BounceSound.Copy();
            BounceType = other.BounceType;
            BurnHeight = other.BurnHeight;
            CameraHeight = other.CameraHeight;
            ConversationID = other.ConversationID;
            CrushPainSound = other.CrushPainSound.Copy();
            Damage = other.Damage;
            DamageFactor = new DamageFactor(other.DamageFactor);
            DamageType = other.DamageType.Copy();
            DeathHeight = other.DeathHeight;
            DeathSound = other.DeathSound.Copy();
            DeathType = other.DeathType.Copy();
            Decal = other.Decal.Copy();
            DefThreshold = other.DefThreshold;
            DesignatedTeam = other.DesignatedTeam;
            DistanceCheck = other.DistanceCheck.Copy();
            DropItem = other.DropItem.Select(val => new DropItem(val)).ToList();
            FastSpeed = other.FastSpeed;
            FloatBobPhase = other.FloatBobPhase;
            FloatBobStrength = other.FloatBobStrength;
            FloatSpeed = other.FloatSpeed;
            Friction = other.Friction;
            FriendlySeeBlocks = other.FriendlySeeBlocks;
            ExplosionDamage = other.ExplosionDamage;
            ExplosionRadius = other.ExplosionRadius;
            Game = new List<string>(Game);
            GibHealth = other.GibHealth;
            Gravity = other.Gravity;
            Health = other.Health;
            Height = other.Height;
            HitObituary = other.HitObituary.Copy();
            HowlSound = other.HowlSound.Copy();
            Mass = other.Mass;
            MaxStepHeight = other.MaxStepHeight;
            MaxDropOffHeight = other.MaxDropOffHeight;
            MaxTargetRange = other.MaxTargetRange;
            MeleeDamage = other.MeleeDamage;
            MeleeRange = other.MeleeRange;
            MeleeSound = other.MeleeSound.Copy();
            MeleeThreshold = other.MeleeThreshold;
            MinMissileChance = other.MinMissileChance;
            MissileHeight = other.MissileHeight;
            MissileType = other.MissileType.Copy();
            Obituary = other.Obituary.Copy();
            PainChance = new PainChance(other.PainChance);
            PainThreshold = other.PainThreshold;
            PainType = other.PainType.Copy();
            PoisonDamage = other.PoisonDamage;
            PoisonDamageType = other.PoisonDamageType.Copy();
            ProjectileKickBack = other.ProjectileKickBack;
            ProjectilePassHeight = other.ProjectilePassHeight;
            PushFactor = other.PushFactor;
            Radius = other.Radius;
            RadiusDamageFactor = other.RadiusDamageFactor;
            ReactionTime = other.ReactionTime;
            RenderRadius = other.RenderRadius;
            RenderStyle = other.RenderStyle;
            RipLevelMax = other.RipLevelMax;
            RipLevelMin = other.RipLevelMin;
            RipperLevel = other.RipperLevel;
            Scale = other.Scale;
            SelfDamageFactor = other.SelfDamageFactor;
            SpawnID = other.SpawnID;
            SpawnInfo = other.SpawnInfo.Map(si => new SpawnInfo(si));
            Species = other.Species.Copy();
            Speed = other.Speed;
            SpriteAngle = other.SpriteAngle;
            SpriteRotation = other.SpriteRotation;
            Stamina = other.Stamina;
            StealthAlpha = other.StealthAlpha;
            StencilColor = other.StencilColor;
            Tag = other.Tag.Copy();
            Translation = new Translation(Translation);
            Threshold = other.Threshold;
            TeleFogDestType = other.TeleFogDestType;
            TeleFogSourceType = other.TeleFogSourceType;
            VisibleAngles = other.VisibleAngles;
            VisiblePitch = other.VisiblePitch;
            VisibleToPlayerClass = new List<UpperString>(other.VisibleToPlayerClass);
            VisibleToTeam = other.VisibleToTeam;
            VSpeed = other.VSpeed;
            WallBounceFactor = other.WallBounceFactor;
            WeaveIndexXY = other.WeaveIndexXY;
            WeaveIndexZ = other.WeaveIndexZ;
            WoundHealth = other.WoundHealth;
            XScale = other.XScale;
            YScale = other.YScale;
        }
    }
}
