using System.Collections.Generic;
using System.Linq;
using Helion.Core.Resource.Decorate.Definitions.Properties.Enums;
using Helion.Core.Resource.Decorate.Definitions.Properties.Types;
using Helion.Core.Resource.Maps.Actions;
using Helion.Core.Util;
using MoreLinq;
using UnityEngine;

namespace Helion.Core.Resource.Decorate.Definitions.Properties
{
    public class ActorProperties
    {
        public int? Accuracy;
        public ThingSpecialActivationType Activation = ThingSpecialActivationType.Default;
        public Optional<UpperString> ActiveSound = Optional<UpperString>.Empty();
        public float Alpha = 1.0f;
        public int? AmmoBackpackAmount;
        public int? AmmoBackpackMaxAmount;
        public int? AmmoDropAmount;
        public int? ArmorMaxAbsorb;
        public int? ArmorMaxBonus;
        public int? ArmorMaxBonusMax;
        public int? ArmorMaxFullAbsorb;
        public int? ArmorMaxSaveAmount;
        public int? ArmorSaveAmount;
        public float? ArmorSavePercent;
        public SpecialArgs Args = new SpecialArgs();
        public Optional<UpperString> AttackSound = Optional<UpperString>.Empty();
        public Color? BloodColor;
        public readonly List<UpperString> BloodType = new List<UpperString>();
        public int BounceCount = int.MaxValue;
        public float BounceFactor = 0.7f;
        public Optional<UpperString> BounceSound = Optional<UpperString>.Empty();
        public BounceType BounceType = BounceType.None;
        public int? BurnHeight;
        public int? CameraHeight;
        public int ConversationID;
        public Optional<UpperString> CrushPainSound = Optional<UpperString>.Empty();
        public int Damage;
        public readonly DamageFactor DamageFactor = new DamageFactor();
        public Optional<UpperString> DamageType = Optional<UpperString>.Empty();
        public int? DeathHeight;
        public Optional<UpperString> DeathSound = Optional<UpperString>.Empty();
        public Optional<UpperString> DeathType = Optional<UpperString>.Empty();
        public Optional<UpperString> Decal = Optional<UpperString>.Empty();
        public int? DefThreshold;
        public int? DesignatedTeam;
        public Optional<UpperString> DistanceCheck = Optional<UpperString>.Empty();
        public readonly List<DropItem> DropItem = new List<DropItem>();
        public int? ExplosionDamage;
        public int? ExplosionRadius;
        public bool FakeInventoryRespawns;
        public float? FastSpeed;
        public int FloatBobPhase;
        public float FloatBobStrength = 1.0f;
        public float FloatSpeed = 4.0f;
        public float Friction = 1.0f;
        public int FriendlySeeBlocks = 10;
        public readonly List<UpperString> Game = new List<UpperString>();
        public int? GibHealth;
        public float Gravity = 1.0f;
        public int Health = 1000;
        public readonly HealthLowMessage HealthLowMessage = new HealthLowMessage();
        public AutoUseType HealthPickupAutoUse = AutoUseType.Never;
        public int Height = 16;
        public Optional<string> HitObituary = Optional<string>.Empty();
        public Optional<UpperString> HowlSound = Optional<UpperString>.Empty();
        public Optional<UpperString> InventoryAltHUDIcon = Optional<UpperString>.Empty();
        public int? InventoryAmount;
        public int? InventoryDefMaxAmount;
        public List<UpperString> InventoryForbiddenTo = new List<UpperString>();
        public int? InventoryGiveQuest;
        public Optional<UpperString> InventoryIcon = Optional<UpperString>.Empty();
        public int InventoryInterHubAmount;
        public int InventoryMaxAmount;
        public Optional<UpperString> InventoryPickupFlash = Optional<UpperString>.Empty();
        public Optional<UpperString> InventoryPickupMessage = Optional<UpperString>.Empty();
        public Optional<UpperString> InventoryPickupSound = Optional<UpperString>.Empty();
        public int? InventoryRespawnTics;
        public List<UpperString> InventoryRestrictedTo = new List<UpperString>();
        public Optional<UpperString> InventoryUseSound = Optional<UpperString>.Empty();
        public int Mass = 100;
        public int MaxStepHeight = 24;
        public int MaxDropOffHeight = 24;
        public int? MaxTargetRange;
        public int? MeleeDamage;
        public int MeleeRange = 44;
        public Optional<UpperString> MeleeSound = Optional<UpperString>.Empty();
        public int? MeleeThreshold;
        public int MinMissileChance = 200;
        public int? MissileHeight;
        public Optional<UpperString> MissileType = Optional<UpperString>.Empty();
        public int? MorphProjectileDuration;
        public Optional<UpperString> MorphProjectileMonsterClass = Optional<UpperString>.Empty();
        public Optional<UpperString> MorphProjectileMorphFlash = Optional<UpperString>.Empty();
        public MorphStyle? MorphProjectileMorphStyle;
        public Optional<UpperString> MorphProjectilePlayerClass = Optional<UpperString>.Empty();
        public Optional<UpperString> MorphProjectileUnMorphFlash = Optional<UpperString>.Empty();
        public Optional<string> Obituary = Optional<string>.Empty();
        public readonly PainChance PainChance = new PainChance();
        public int PainThreshold;
        public Optional<UpperString> PainType = Optional<UpperString>.Empty();
        public float PlayerAirCapacity = 1.0f;
        public float PlayerAttackZOffset;
        public DecorateRange<int> PlayerColorRange = new DecorateRange<int>(0, 0);
        public Optional<UpperString> PlayerCrouchSprite = Optional<UpperString>.Empty();
        public readonly DamageScreenColor PlayerDamageScreenColor = new DamageScreenColor();
        public Optional<UpperString> PlayerDisplayName = Optional<UpperString>.Empty();
        public Optional<UpperString> PlayerFace = Optional<UpperString>.Empty();
        public DecorateRange<float> PlayerFallingScreamSpeed = new DecorateRange<float>(35, 45);
        public Optional<UpperString> PlayerFlechetteType = Optional<UpperString>.Empty();
        public RunSpeed PlayerForwardMove = new RunSpeed(1.0f, 1.0f);
        public float PlayerGruntSpeed = 12.0f;
        public Optional<UpperString> PlayerHealRadiusType = Optional<UpperString>.Empty();
        public HexenArmor? PlayerHexenArmor;
        public float PlayerJumpZ = 8.0f;
        public int PlayerMaxHealth = 100;
        public Optional<UpperString> PlayerMorphWeapon = Optional<UpperString>.Empty();
        public int PlayerMugShotMaxHealth;
        public Optional<UpperString> PlayerPortrait = Optional<UpperString>.Empty();
        public int PlayerRunHealth;
        public Optional<UpperString> PlayerScoreIcon = Optional<UpperString>.Empty();
        public RunSpeed PlayerSideMove = new RunSpeed(1.0f, 1.0f);
        public Optional<UpperString> PlayerSoundClass = Optional<UpperString>.Empty();
        public Optional<UpperString> PlayerSpawnClass = Optional<UpperString>.Empty();
        public readonly Dictionary<UpperString, int> PlayerStartItem = new Dictionary<UpperString, int>();
        public int PlayerTeleportFreezeTime = 18;
        public float PlayerUseRange = 64.0f;
        public readonly Dictionary<int, List<UpperString>> PlayerWeaponSlot = new Dictionary<int, List<UpperString>>();
        public float PlayerViewBob = 1.0f;
        public float PlayerViewHeight = 41.0f;
        public PoisonDamage? PoisonDamage;
        public Optional<UpperString> PoisonDamageType = Optional<UpperString>.Empty();
        public PowerupColor? PowerupColor;
        public PowerupColormap? PowerupColormap;
        public int? PowerupDuration;
        public RenderStyle PowerupMode = RenderStyle.Normal;
        public int? PowerupStrength;
        public Optional<UpperString> PowerupType = Optional<UpperString>.Empty();
        public bool PowerSpeedNoTrail;
        public int? ProjectileKickBack;
        public int? ProjectilePassHeight;
        public float PushFactor = 0.25f;
        public int? PuzzleItemNumber;
        public Optional<UpperString> PuzzleItemFailMessage = Optional<UpperString>.Empty();
        public int Radius = 20;
        public float RadiusDamageFactor = 1.0f;
        public int ReactionTime = 8;
        public float RenderRadius;
        public RenderStyle RenderStyle = RenderStyle.Normal;
        public int RipLevelMax;
        public int RipLevelMin;
        public int? RipperLevel;
        public float Scale = 1.0f;
        public float SelfDamageFactor = 1.0f;
        public int SpawnID;
        public Optional<SpawnInfo> SpawnInfo = Optional<SpawnInfo>.Empty();
        public Optional<UpperString> Species = Optional<UpperString>.Empty();
        public float Speed;
        public int? SpriteAngle;
        public int? SpriteRotation;
        public int? Stamina;
        public float StealthAlpha;
        public Color? StencilColor;
        public Optional<UpperString> Tag = Optional<UpperString>.Empty();
        public UpperString TeleFogDestType = "TELEPORTFOG";
        public UpperString TeleFogSourceType = "TELEPORTFOG";
        public int Threshold;
        public readonly Translation Translation = new Translation();
        public DecorateRange<int>? VisibleAngles;
        public DecorateRange<int>? VisiblePitch;
        public List<UpperString> VisibleToPlayerClass = new List<UpperString>();
        public int? VisibleToTeam;
        public float? VSpeed;
        public float WallBounceFactor = 0.7f;
        public int? WeaponAmmoGive;
        public int? WeaponAmmoGive1;
        public int? WeaponAmmoGive2;
        public Optional<UpperString> WeaponAmmoType = Optional<UpperString>.Empty();
        public Optional<UpperString> WeaponAmmoType1 = Optional<UpperString>.Empty();
        public Optional<UpperString> WeaponAmmoType2 = Optional<UpperString>.Empty();
        public float WeaponBobRangeX = 1.0f;
        public float WeaponBobRangeY = 1.0f;
        public float WeaponBobSpeed = 1.0f;
        public BobStyle WeaponBobStyle = BobStyle.Normal;
        public bool WeaponDefaultKickBack;
        public int? WeaponKickBack;
        public float? WeaponLookScale;
        public int? WeaponMinSelectionAmmo1;
        public int? WeaponMinSelectionAmmo2;
        public Optional<UpperString> WeaponReadySound = Optional<UpperString>.Empty();
        public int? WeaponSelectionOrder;
        public Optional<UpperString> WeaponSisterWeapon = Optional<UpperString>.Empty();
        public int? WeaponSlotNumber;
        public float? WeaponSlotPriority;
        public Optional<UpperString> WeaponUpSound = Optional<UpperString>.Empty();
        public int? WeaponYAdjust;
        public int? WeaponPieceNumber;
        public Optional<UpperString> WeaponPieceWeapon = Optional<UpperString>.Empty();
        public int? WeaveIndexXY;
        public int? WeaveIndexZ;
        public int WoundHealth;
        public float XScale = 1.0f;
        public float YScale = 1.0f;

        public ActorProperties()
        {
        }

        public ActorProperties(ActorProperties other)
        {
            Accuracy = other.Accuracy;
            Activation = other.Activation;
            ActiveSound = other.ActiveSound.Copy();
            Alpha = other.Alpha;
            AmmoBackpackAmount = other.AmmoBackpackAmount;
            AmmoBackpackMaxAmount = other.AmmoBackpackMaxAmount;
            AmmoDropAmount = other.AmmoDropAmount;
            ArmorMaxAbsorb = other.ArmorMaxAbsorb;
            ArmorMaxBonus = other.ArmorMaxBonus;
            ArmorMaxBonusMax = other.ArmorMaxBonusMax;
            ArmorMaxSaveAmount = other.ArmorMaxSaveAmount;
            ArmorMaxFullAbsorb = other.ArmorMaxFullAbsorb;
            ArmorSaveAmount = other.ArmorSaveAmount;
            ArmorSavePercent = other.ArmorSavePercent;
            Args = new SpecialArgs(other.Args);
            AttackSound = other.AttackSound.Copy();
            BloodColor = other.BloodColor;
            BloodType = new List<UpperString>(other.BloodType);
            BounceCount = other.BounceCount;
            BounceFactor = other.BounceFactor;
            BounceSound = other.BounceSound.Copy();
            BounceType = other.BounceType;
            BurnHeight = other.BurnHeight;
            CameraHeight = other.CameraHeight;
            ConversationID = other.ConversationID;
            CrushPainSound = other.CrushPainSound.Copy();
            Damage = other.Damage;
            DamageFactor = new DamageFactor(other.DamageFactor);
            DamageType = other.DamageType.Copy();
            DeathHeight = other.DeathHeight;
            DeathSound = other.DeathSound.Copy();
            DeathType = other.DeathType.Copy();
            Decal = other.Decal.Copy();
            DefThreshold = other.DefThreshold;
            DesignatedTeam = other.DesignatedTeam;
            DistanceCheck = other.DistanceCheck.Copy();
            DropItem = other.DropItem.Select(val => new DropItem(val)).ToList();
            ExplosionDamage = other.ExplosionDamage;
            ExplosionRadius = other.ExplosionRadius;
            FakeInventoryRespawns = other.FakeInventoryRespawns;
            FastSpeed = other.FastSpeed;
            FloatBobPhase = other.FloatBobPhase;
            FloatBobStrength = other.FloatBobStrength;
            FloatSpeed = other.FloatSpeed;
            Friction = other.Friction;
            FriendlySeeBlocks = other.FriendlySeeBlocks;
            Game = new List<UpperString>(Game);
            GibHealth = other.GibHealth;
            Gravity = other.Gravity;
            Health = other.Health;
            HealthLowMessage = new HealthLowMessage(other.HealthLowMessage);
            HealthPickupAutoUse = other.HealthPickupAutoUse;
            Height = other.Height;
            HitObituary = other.HitObituary.Copy();
            HowlSound = other.HowlSound.Copy();
            InventoryAltHUDIcon = other.InventoryAltHUDIcon.Copy();
            InventoryAmount = other.InventoryAmount;
            InventoryDefMaxAmount = other.InventoryDefMaxAmount;
            InventoryForbiddenTo = new List<UpperString>(other.InventoryForbiddenTo);
            InventoryGiveQuest = other.InventoryGiveQuest;
            InventoryIcon = other.InventoryIcon.Copy();
            InventoryInterHubAmount = other.InventoryInterHubAmount;
            InventoryMaxAmount = other.InventoryMaxAmount;
            InventoryPickupFlash = other.InventoryPickupFlash.Copy();
            InventoryPickupMessage = other.InventoryPickupMessage.Copy();
            InventoryPickupSound = other.InventoryPickupSound.Copy();
            InventoryRespawnTics = other.InventoryRespawnTics;
            InventoryRestrictedTo = new List<UpperString>(other.InventoryRestrictedTo);
            InventoryUseSound = other.InventoryUseSound.Copy();
            Mass = other.Mass;
            MaxStepHeight = other.MaxStepHeight;
            MaxDropOffHeight = other.MaxDropOffHeight;
            MaxTargetRange = other.MaxTargetRange;
            MeleeDamage = other.MeleeDamage;
            MeleeRange = other.MeleeRange;
            MeleeSound = other.MeleeSound.Copy();
            MeleeThreshold = other.MeleeThreshold;
            MinMissileChance = other.MinMissileChance;
            MissileHeight = other.MissileHeight;
            MissileType = other.MissileType.Copy();
            MorphProjectileDuration = other.MorphProjectileDuration;
            MorphProjectileMonsterClass = other.MorphProjectileMonsterClass.Copy();
            MorphProjectileMorphFlash = other.MorphProjectileMorphFlash.Copy();
            MorphProjectileMorphStyle = other.MorphProjectileMorphStyle;
            MorphProjectilePlayerClass = other.MorphProjectilePlayerClass.Copy();
            MorphProjectileUnMorphFlash = other.MorphProjectileUnMorphFlash.Copy();
            Obituary = other.Obituary.Copy();
            PainChance = new PainChance(other.PainChance);
            PainThreshold = other.PainThreshold;
            PainType = other.PainType.Copy();
            PlayerAirCapacity = other.PlayerAirCapacity;
            PlayerAttackZOffset = other.PlayerAttackZOffset;
            PlayerColorRange = other.PlayerColorRange;
            PlayerCrouchSprite = other.PlayerCrouchSprite.Copy();
            PlayerDamageScreenColor = new DamageScreenColor(other.PlayerDamageScreenColor);
            PlayerDisplayName = other.PlayerDisplayName.Copy();
            PlayerFace = other.PlayerFace.Copy();
            PlayerFallingScreamSpeed = other.PlayerFallingScreamSpeed;
            PlayerFlechetteType = other.PlayerFlechetteType.Copy();
            PlayerForwardMove = other.PlayerForwardMove;
            PlayerGruntSpeed = other.PlayerGruntSpeed;
            PlayerHealRadiusType = other.PlayerHealRadiusType.Copy();
            PlayerHexenArmor = other.PlayerHexenArmor;
            PlayerJumpZ = other.PlayerJumpZ;
            PlayerMaxHealth = other.PlayerMaxHealth;
            PlayerMorphWeapon = other.PlayerMorphWeapon.Copy();
            PlayerMugShotMaxHealth = other.PlayerMugShotMaxHealth;
            PlayerPortrait = other.PlayerPortrait.Copy();
            PlayerRunHealth = other.PlayerRunHealth;
            PlayerScoreIcon = other.PlayerScoreIcon.Copy();
            PlayerSideMove = other.PlayerSideMove;
            PlayerSoundClass = other.PlayerSoundClass.Copy();
            PlayerSpawnClass = other.PlayerSpawnClass.Copy();
            PlayerStartItem = new Dictionary<UpperString, int>(other.PlayerStartItem);
            PlayerTeleportFreezeTime = other.PlayerTeleportFreezeTime;
            PlayerUseRange = other.PlayerUseRange;
            PlayerWeaponSlot = CopyWeaponSlot(other.PlayerWeaponSlot);
            PlayerViewBob = other.PlayerViewBob;
            PlayerViewHeight = other.PlayerViewHeight;
            PoisonDamage = other.PoisonDamage;
            PoisonDamageType = other.PoisonDamageType.Copy();
            PowerupColor = other.PowerupColor;
            PowerupColormap = other.PowerupColormap;
            PowerupDuration = other.PowerupDuration;
            PowerupMode = other.PowerupMode;
            PowerupStrength = other.PowerupStrength;
            PowerupType = other.PowerupType.Copy();
            PowerSpeedNoTrail = other.PowerSpeedNoTrail;
            ProjectileKickBack = other.ProjectileKickBack;
            ProjectilePassHeight = other.ProjectilePassHeight;
            PushFactor = other.PushFactor;
            PuzzleItemNumber = other.PuzzleItemNumber;
            PuzzleItemFailMessage = other.PuzzleItemFailMessage.Copy();
            Radius = other.Radius;
            RadiusDamageFactor = other.RadiusDamageFactor;
            ReactionTime = other.ReactionTime;
            RenderRadius = other.RenderRadius;
            RenderStyle = other.RenderStyle;
            RipLevelMax = other.RipLevelMax;
            RipLevelMin = other.RipLevelMin;
            RipperLevel = other.RipperLevel;
            Scale = other.Scale;
            SelfDamageFactor = other.SelfDamageFactor;
            SpawnID = other.SpawnID;
            SpawnInfo = other.SpawnInfo.Map(si => new SpawnInfo(si));
            Species = other.Species.Copy();
            Speed = other.Speed;
            SpriteAngle = other.SpriteAngle;
            SpriteRotation = other.SpriteRotation;
            Stamina = other.Stamina;
            StealthAlpha = other.StealthAlpha;
            StencilColor = other.StencilColor;
            Tag = other.Tag.Copy();
            Translation = new Translation(Translation);
            Threshold = other.Threshold;
            TeleFogDestType = other.TeleFogDestType;
            TeleFogSourceType = other.TeleFogSourceType;
            VisibleAngles = other.VisibleAngles;
            VisiblePitch = other.VisiblePitch;
            VisibleToPlayerClass = new List<UpperString>(other.VisibleToPlayerClass);
            VisibleToTeam = other.VisibleToTeam;
            VSpeed = other.VSpeed;
            WallBounceFactor = other.WallBounceFactor;
            WeaponAmmoGive = other.WeaponAmmoGive;
            WeaponAmmoGive1 = other.WeaponAmmoGive1;
            WeaponAmmoGive2 = other.WeaponAmmoGive2;
            WeaponAmmoType = other.WeaponAmmoType.Copy();
            WeaponAmmoType1 = other.WeaponAmmoType1.Copy();
            WeaponAmmoType2 = other.WeaponAmmoType2.Copy();
            WeaponBobRangeX = other.WeaponBobRangeX;
            WeaponBobRangeY = other.WeaponBobRangeY;
            WeaponBobSpeed = other.WeaponBobSpeed;
            WeaponBobStyle = other.WeaponBobStyle;
            WeaponDefaultKickBack = other.WeaponDefaultKickBack;
            WeaponKickBack = other.WeaponKickBack;
            WeaponLookScale = other.WeaponLookScale;
            WeaponMinSelectionAmmo1 = other.WeaponMinSelectionAmmo1;
            WeaponMinSelectionAmmo2 = other.WeaponMinSelectionAmmo2;
            WeaponReadySound = other.WeaponReadySound.Copy();
            WeaponSelectionOrder = other.WeaponSelectionOrder;
            WeaponSisterWeapon = other.WeaponSisterWeapon.Copy();
            WeaponSlotNumber = other.WeaponSlotNumber;
            WeaponSlotPriority = other.WeaponSlotPriority;
            WeaponUpSound = other.WeaponUpSound.Copy();
            WeaponYAdjust = other.WeaponYAdjust;
            WeaponPieceNumber = other.WeaponPieceNumber;
            WeaponPieceWeapon = other.WeaponPieceWeapon.Copy();
            WeaveIndexXY = other.WeaveIndexXY;
            WeaveIndexZ = other.WeaveIndexZ;
            WoundHealth = other.WoundHealth;
            XScale = other.XScale;
            YScale = other.YScale;
        }

        private static Dictionary<int, List<UpperString>> CopyWeaponSlot(Dictionary<int, List<UpperString>> otherWeaponSlot)
        {
            Dictionary<int, List<UpperString>> dict = new Dictionary<int, List<UpperString>>();
            otherWeaponSlot.ForEach(kv => dict[kv.Key] = new List<UpperString>(kv.Value));
            return dict;
        }
    }
}
